# Generated by Django 5.2 on 2025-05-23 02:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('device_name', models.CharField(max_length=100)),
                ('os_version', models.CharField(max_length=50)),
                ('ram_mb', models.IntegerField()),
                ('storage_mb', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('keep_data_on_leave', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SongProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(blank=True, max_length=200, null=True)),
                ('duration_seconds', models.IntegerField()),
                ('file_size_kb', models.IntegerField()),
                ('file_format', models.CharField(max_length=50)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='desktop_lan_connect.deviceprofile')),
            ],
        ),
    ]
