# Generated by Django 5.2 on 2025-05-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop_lan_connect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceprofile',
            name='ram_mb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deviceprofile',
            name='storage_mb',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
