# Generated by Django 5.2 on 2025-05-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop_lan_connect', '0002_alter_deviceprofile_ram_mb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceprofile',
            name='device_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
