# Generated by Django 5.2 on 2025-05-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop_lan_connect', '0003_alter_deviceprofile_device_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='songprofile',
            name='file_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
