# Generated by Django 5.2 on 2025-05-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop_lan_connect', '0004_songprofile_file_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='songprofile',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
