# Generated by Django 5.2 on 2025-05-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop_lan_connect', '0005_songprofile_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceprofile',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
