# Generated by Django 5.2 on 2025-05-26 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop_lan_connect', '0006_deviceprofile_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='songprofile',
            name='device_file_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='songprofile',
            name='port',
            field=models.IntegerField(default=8000),
        ),
    ]
