# Generated by Django 5.2 on 2025-05-28 16:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkedVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('duration', models.PositiveIntegerField()),
                ('uploader', models.CharField(max_length=255)),
                ('thumbnail', models.URLField()),
                ('webpage_url', models.URLField(unique=True)),
                ('upload_date', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
