name: Trigger Check on Push

on:
  push:
    branches:
      - desktop

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger main workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run "Check yt-dlp Version" --ref main --repo ${{ github.repository }}
